---
title: "CombinedClassifier"
author: "Anyan Liu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{CombinedClassifier}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## 1. Introduction

`CombiningClassifier` is an R function that implete Logistic.


## 2. Preparing Data

The first step is to create a synthetic dataset for demonstration.
```{r data-preparation, echo=TRUE}

# Simulating training and test datasets
set.seed(123)  
X <- data.frame(
  x1 = rnorm(100),  
  x2 = rnorm(100)
)
y <- sample(c(0, 1), 100, replace = TRUE)  

```



## 3.Using Package
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(CombiningClassifier)

result <- CombiningClassifier(X, y)
# Display results
print(result)

```



## 4. Comparison efficiency
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(bench)

set.seed(123)
X <- data.frame(x1 = rnorm(100), x2 = rnorm(100))
y <- sample(c(0, 1), 100, replace = TRUE)

performance_comparison <- bench::mark(
  my_logistic = CombiningClassifier(X, y),
  glm = glm(y ~ ., data = X, family = binomial),
  iterations = 10
)
cat("\nPerformance comparison:\n")
print(performance_comparison)

```



## 5. Comaprison correctness
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)


set.seed(123)
X <- data.frame(x1 = rnorm(100), x2 = rnorm(100))
y <- sample(c(0, 1), 100, replace = TRUE)


CombiningClassifier_result <- CombiningClassifier(X, y)


glm_result <- glm(y ~ ., data = X, family = binomial)


fitted_CombiningClassifier <- CombiningClassifier_result$fitted.values
fitted_glm <- fitted(glm_result)


comparison_correctness <- all.equal(fitted_CombiningClassifier, fitted_glm, tolerance = 1e-4)
cat("Comparison using all.equal():\n")
print(comparison_correctness)








```



## 6.Use testthat to do unit testing 
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(devtools)
devtools::test()

```


