name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r: 'devel' }
          - { os: ubuntu-latest, r: 'release' }
          - { os: ubuntu-latest, r: 'oldrel' }
          - { os: macOS-latest, r: 'release' }
          - { os: windows-latest, r: 'release' }

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: testthat

      - name: Run R CMD build
        run: R CMD build .

      - name: Run R CMD check
        run: R CMD check *tar.gz --no-manual

steps:
  - name: Install system dependencies (Ubuntu)
    run: sudo apt-get install -y libcurl4-openssl-dev libxml2-dev
  - name: Install system dependencies (macOS)
    run: brew install libxml2
  - name: Install system dependencies (Windows)
    run: choco install openssl

